### PR TITLE
Fixes a bug in recent Kotlin/Dart versions

### PR DESCRIPTION
**Pull request by noordawod**
The current version of the plugin doesn't compile anymore with the most recent versions of Dart and Kotlin. This small pr fixes that.

### CODE REVIEW

**Comment by noordawod** [comment]
@IsaiasSantana what do you think?

**Comment by noordawod** [comment]
@IsaiasSantana Bump.

**Comment by noordawod** [comment]
@IsaiasSantana Bump.

**Comment by noordawod** [comment]
@IsaiasSantana Bump, for new year :)

**Comment by via-guy** [comment]
@IsaiasSantana can you please merge this in?

**Comment by IsaiasSantana** [comment]
Hi everyone! Sorry for late response. Thanks for the fix! I'll merge this as soon as possible. I was a little sick these days and busy with a big feature in another project.

**Review by IsaiasSantana — APPROVED** [review]

**Review by alarkirikal — APPROVED** [review]

**Comment by noordawod** [comment]
Come on... It's been ages.

**Pull request merged**
